<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\CourseLevel;
use App\Models\Course;
use Illuminate\Database\Seeder;

final class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            [
                'name' => 'Introduction to Laravel',
                'user_id' => 1,
                'category_id' => 1,
                'thumbnail' => 'https://example.com/laravel-intro.jpg',
                'description' => 'Learn the basics of Laravel framework',
                'long_description' => 'This comprehensive course covers everything you need to know to get started with Laravel, including routing, controllers, models, and more.',
                'price' => 99.99,
                'is_free' => false,
                'level' => CourseLevel::BEGINNER->value,
                'language' => 'en',
                'requirements' => json_encode(['Basic PHP knowledge', 'HTML/CSS basics']),
            ],
            [
                'name' => 'Advanced JavaScript',
                'user_id' => 2,
                'category_id' => 1,
                'thumbnail' => 'https://example.com/js-advanced.jpg',
                'description' => 'Master advanced JavaScript concepts',
                'long_description' => 'Dive deep into closures, prototypes, async programming, and modern JavaScript features.',
                'price' => 149.99,
                'is_free' => false,
                'level' => CourseLevel::ADVANCED->value,
                'language' => 'en',
                'requirements' => json_encode(['Intermediate JavaScript', 'ES6 knowledge']),
            ],
            [
                'name' => 'Python for Data Science',
                'user_id' => 3,
                'category_id' => 2,
                'thumbnail' => 'https://example.com/python-ds.jpg',
                'description' => 'Learn Python for data analysis',
                'long_description' => 'Master Python libraries like Pandas, NumPy, and Matplotlib for data science projects.',
                'price' => 129.99,
                'is_free' => false,
                'level' => CourseLevel::INTERMEDIATE->value,
                'language' => 'en',
                'requirements' => json_encode(['Basic Python', 'Math fundamentals']),
            ],
            [
                'name' => 'Machine Learning with TensorFlow',
                'user_id' => 4,
                'category_id' => 3,
                'thumbnail' => 'https://example.com/tf-ml.jpg',
                'description' => 'Build ML models with TensorFlow',
                'long_description' => 'Learn to create neural networks, train models, and deploy ML applications using TensorFlow.',
                'price' => 199.99,
                'is_free' => false,
                'level' => CourseLevel::ADVANCED->value,
                'language' => 'en',
                'requirements' => json_encode(['Python', 'Linear Algebra']),
            ],
            [
                'name' => 'iOS App Development',
                'user_id' => 5,
                'category_id' => 4,
                'thumbnail' => 'https://example.com/ios-dev.jpg',
                'description' => 'Create iOS apps with Swift',
                'long_description' => 'From basics to advanced iOS development, learn SwiftUI, UIKit, and app store deployment.',
                'price' => 179.99,
                'is_free' => false,
                'level' => CourseLevel::INTERMEDIATE->value,
                'language' => 'en',
                'requirements' => json_encode(['Swift basics', 'Xcode familiarity']),
            ],
            [
                'name' => 'Ethical Hacking Fundamentals',
                'user_id' => 6,
                'category_id' => 5,
                'thumbnail' => 'https://example.com/hacking.jpg',
                'description' => 'Learn ethical hacking techniques',
                'long_description' => 'Discover penetration testing, vulnerability assessment, and cybersecurity best practices.',
                'price' => 159.99,
                'is_free' => false,
                'level' => CourseLevel::BEGINNER->value,
                'language' => 'en',
                'requirements' => json_encode(['Basic networking', 'Linux knowledge']),
            ],
            [
                'name' => 'AWS Cloud Architecture',
                'user_id' => 7,
                'category_id' => 6,
                'thumbnail' => 'https://example.com/aws-cloud.jpg',
                'description' => 'Design scalable cloud solutions',
                'long_description' => 'Master AWS services, architecture patterns, and best practices for cloud computing.',
                'price' => 189.99,
                'is_free' => false,
                'level' => CourseLevel::ADVANCED->value,
                'language' => 'en',
                'requirements' => json_encode(['Basic cloud concepts', 'Networking']),
            ],
            [
                'name' => 'Docker and Kubernetes',
                'user_id' => 8,
                'category_id' => 7,
                'thumbnail' => 'https://example.com/docker-k8s.jpg',
                'description' => 'Containerization and orchestration',
                'long_description' => 'Learn Docker containers, Kubernetes orchestration, and DevOps practices.',
                'price' => 169.99,
                'is_free' => false,
                'level' => CourseLevel::INTERMEDIATE->value,
                'language' => 'en',
                'requirements' => json_encode(['Linux basics', 'Command line']),
            ],
            [
                'name' => 'Computer Vision with OpenCV',
                'user_id' => 9,
                'category_id' => 8,
                'thumbnail' => 'https://example.com/opencv-cv.jpg',
                'description' => 'Build computer vision applications',
                'long_description' => 'Master image processing, object detection, and AI vision projects with OpenCV.',
                'price' => 139.99,
                'is_free' => false,
                'level' => CourseLevel::INTERMEDIATE->value,
                'language' => 'en',
                'requirements' => json_encode(['Python', 'Math']),
            ],
            [
                'name' => 'Blockchain Development',
                'user_id' => 10,
                'category_id' => 9,
                'thumbnail' => 'https://example.com/blockchain.jpg',
                'description' => 'Create blockchain applications',
                'long_description' => 'Learn smart contracts, DApps, and blockchain technology fundamentals.',
                'price' => 199.99,
                'is_free' => false,
                'level' => CourseLevel::ADVANCED->value,
                'language' => 'en',
                'requirements' => json_encode(['Programming basics', 'Cryptography']),
            ],
            [
                'name' => 'Unity Game Development',
                'user_id' => 1,
                'category_id' => 10,
                'thumbnail' => 'https://example.com/unity-games.jpg',
                'description' => 'Create games with Unity',
                'long_description' => 'From 2D to 3D games, learn Unity engine, C# scripting, and game design.',
                'price' => 149.99,
                'is_free' => false,
                'level' => CourseLevel::BEGINNER->value,
                'language' => 'en',
                'requirements' => json_encode(['Basic programming', 'Creativity']),
            ],
            [
                'name' => 'React Native Mobile Apps',
                'user_id' => 2,
                'category_id' => 4,
                'thumbnail' => 'https://example.com/react-native.jpg',
                'description' => 'Cross-platform mobile development',
                'long_description' => 'Build iOS and Android apps with React Native and JavaScript.',
                'price' => 129.99,
                'is_free' => false,
                'level' => CourseLevel::INTERMEDIATE->value,
                'language' => 'en',
                'requirements' => json_encode(['JavaScript', 'React basics']),
            ],
            [
                'name' => 'Data Visualization with D3.js',
                'user_id' => 3,
                'category_id' => 2,
                'thumbnail' => 'https://example.com/d3-viz.jpg',
                'description' => 'Create interactive data visualizations',
                'long_description' => 'Master D3.js for creating stunning, interactive data visualizations on the web.',
                'price' => 119.99,
                'is_free' => false,
                'level' => CourseLevel::INTERMEDIATE->value,
                'language' => 'en',
                'requirements' => json_encode(['JavaScript', 'SVG basics']),
            ],
            [
                'name' => 'Natural Language Processing',
                'user_id' => 4,
                'category_id' => 3,
                'thumbnail' => 'https://example.com/nlp.jpg',
                'description' => 'AI text analysis and generation',
                'long_description' => 'Learn NLP techniques, sentiment analysis, and language models.',
                'price' => 179.99,
                'is_free' => false,
                'level' => CourseLevel::ADVANCED->value,
                'language' => 'en',
                'requirements' => json_encode(['Python', 'Machine Learning basics']),
            ],
            [
                'name' => 'Android Development with Kotlin',
                'user_id' => 5,
                'category_id' => 4,
                'thumbnail' => 'https://example.com/android-kotlin.jpg',
                'description' => 'Modern Android app development',
                'long_description' => 'Build Android apps with Kotlin, Jetpack Compose, and modern Android architecture.',
                'price' => 159.99,
                'is_free' => false,
                'level' => CourseLevel::INTERMEDIATE->value,
                'language' => 'en',
                'requirements' => json_encode(['Java/Kotlin basics', 'Android Studio']),
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
